set_false_path -from [get_pins -hierarchical -filter {NAME =~ *zzlab_env_ctrl*/*ap_rst_n*reg*/C}]

# set_false_path -from [get_pins {app/bd_ila_wrapper_U/bd_ila_i/zzlab_env_ctrl_0/inst/int_out_ap_rst_n_reg[*]/C}] -to [get_pins {app/bd_ila_wrapper_U/bd_ila_i/tlp_dma_wr_0/tlp_dma_wr_U/inst/*/CLR}]
set_false_path -from [get_pins {app/bd_ila_wrapper_U/bd_ila_i/tlp_dma_wr_0/tlp_dma_wr_U/inst/size_int_reg[*]/C}] -to [get_pins {app/bd_ila_wrapper_U/bd_ila_i/tlp_dma_wr_0/tlp_dma_wr_U/inst/desc_bytes_int_reg[*]/D}]
set_false_path -from [get_pins {app/bd_ila_wrapper_U/bd_ila_i/tlp_dma_wr_0/tlp_dma_wr_U/inst/desc_bytes_int_reg[*]/C}] -to [get_pins {app/bd_ila_wrapper_U/bd_ila_i/tlp_dma_wr_0/tlp_dma_wr_U/inst/desc_addr_next_int_reg[*]/D}]
set_false_path -from [get_pins {app/bd_ila_wrapper_U/bd_ila_i/tlp_dma_wr_0/tlp_dma_wr_U/inst/size_int_reg[*]/C}] -to [get_pins {app/bd_ila_wrapper_U/bd_ila_i/tlp_dma_wr_0/tlp_dma_wr_U/inst/size_int_reg[*]/D}]
set_false_path -from [get_pins {app/bd_ila_wrapper_U/bd_ila_i/tlp_dma_wr_0/tlp_dma_wr_U/inst/size_int_reg[*]/C}] -to [get_pins {app/bd_ila_wrapper_U/bd_ila_i/tlp_dma_wr_0/tlp_dma_wr_U/inst/desc_addr_next_int_reg[*]/D}]
set_false_path -from [get_pins {app/bd_ila_wrapper_U/bd_ila_i/tlp_dma_wr_0/tlp_dma_wr_U/inst/desc_bytes_int_reg[*]/C}] -to [get_pins {app/bd_ila_wrapper_U/bd_ila_i/tlp_dma_wr_0/tlp_dma_wr_U/inst/desc_bytes_int_reg[*]/D}]
set_false_path -from [get_pins {app/bd_ila_wrapper_U/bd_ila_i/tlp_dma_wr_0/tlp_dma_wr_U/inst/desc_bytes_int_reg[*]/C}] -to [get_pins {app/bd_ila_wrapper_U/bd_ila_i/tlp_dma_wr_0/tlp_dma_wr_U/inst/size_int_reg[*]/D}]
set_false_path -from [get_pins {app/bd_ila_wrapper_U/bd_ila_i/tlp_dma_wr_0/tlp_dma_wr_U/inst/tlp_hdr_len_reg[*]/C}] -to [get_pins {app/bd_ila_wrapper_U/bd_ila_i/tlp_dma_wr_0/tlp_dma_wr_U/inst/desc_addr_int_reg[*]/CE}]

# set_false_path -from [get_pins {app/bd_ila_wrapper_U/bd_ila_i/zzlab_env_ctrl_0/inst/int_out_ap_rst_n_reg[*]/C}] -to [get_pins {app/bd_ila_wrapper_U/bd_ila_i/tlp_dma_rd_0/tlp_dma_rd_U/inst/*/CLR}]
set_false_path -from [get_pins {app/bd_ila_wrapper_U/bd_ila_i/tlp_dma_rd_0/tlp_dma_rd_U/inst/size_int_reg[*]/C}] -to [get_pins {app/bd_ila_wrapper_U/bd_ila_i/tlp_dma_rd_0/tlp_dma_rd_U/inst/desc_bytes_int_reg[*]/D}]
set_false_path -from [get_pins {app/bd_ila_wrapper_U/bd_ila_i/tlp_dma_rd_0/tlp_dma_rd_U/inst/desc_bytes_int_reg[*]/C}] -to [get_pins {app/bd_ila_wrapper_U/bd_ila_i/tlp_dma_rd_0/tlp_dma_rd_U/inst/desc_addr_next_int_reg[*]/D}]
set_false_path -from [get_pins {app/bd_ila_wrapper_U/bd_ila_i/tlp_dma_rd_0/tlp_dma_rd_U/inst/size_int_reg[*]/C}] -to [get_pins {app/bd_ila_wrapper_U/bd_ila_i/tlp_dma_rd_0/tlp_dma_rd_U/inst/size_int_reg[*]/D}]
set_false_path -from [get_pins {app/bd_ila_wrapper_U/bd_ila_i/tlp_dma_rd_0/tlp_dma_rd_U/inst/size_int_reg[*]/C}] -to [get_pins {app/bd_ila_wrapper_U/bd_ila_i/tlp_dma_rd_0/tlp_dma_rd_U/inst/desc_addr_next_int_reg[*]/D}]
set_false_path -from [get_pins {app/bd_ila_wrapper_U/bd_ila_i/tlp_dma_rd_0/tlp_dma_rd_U/inst/desc_bytes_int_reg[*]/C}] -to [get_pins {app/bd_ila_wrapper_U/bd_ila_i/tlp_dma_rd_0/tlp_dma_rd_U/inst/desc_bytes_int_reg[*]/D}]
set_false_path -from [get_pins {app/bd_ila_wrapper_U/bd_ila_i/tlp_dma_rd_0/tlp_dma_rd_U/inst/desc_bytes_int_reg[*]/C}] -to [get_pins {app/bd_ila_wrapper_U/bd_ila_i/tlp_dma_rd_0/tlp_dma_rd_U/inst/size_int_reg[*]/D}]

# set_false_path -from [get_pins {app/bd_ila_wrapper_U/bd_ila_i/zzlab_env_ctrl_0/inst/int_out_ap_rst_n_reg[*]/C}] -to [get_pins {app/bd_ila_wrapper_U/bd_ila_i/tlp_dma_wr_1/tlp_dma_wr_U/inst/*/CLR}]
set_false_path -from [get_pins {app/bd_ila_wrapper_U/bd_ila_i/tlp_dma_wr_1/tlp_dma_wr_U/inst/size_int_reg[*]/C}] -to [get_pins {app/bd_ila_wrapper_U/bd_ila_i/tlp_dma_wr_1/tlp_dma_wr_U/inst/desc_bytes_int_reg[*]/D}]
set_false_path -from [get_pins {app/bd_ila_wrapper_U/bd_ila_i/tlp_dma_wr_1/tlp_dma_wr_U/inst/desc_bytes_int_reg[*]/C}] -to [get_pins {app/bd_ila_wrapper_U/bd_ila_i/tlp_dma_wr_1/tlp_dma_wr_U/inst/desc_addr_next_int_reg[*]/D}]
set_false_path -from [get_pins {app/bd_ila_wrapper_U/bd_ila_i/tlp_dma_wr_1/tlp_dma_wr_U/inst/size_int_reg[*]/C}] -to [get_pins {app/bd_ila_wrapper_U/bd_ila_i/tlp_dma_wr_1/tlp_dma_wr_U/inst/size_int_reg[*]/D}]
set_false_path -from [get_pins {app/bd_ila_wrapper_U/bd_ila_i/tlp_dma_wr_1/tlp_dma_wr_U/inst/size_int_reg[*]/C}] -to [get_pins {app/bd_ila_wrapper_U/bd_ila_i/tlp_dma_wr_1/tlp_dma_wr_U/inst/desc_addr_next_int_reg[*]/D}]
set_false_path -from [get_pins {app/bd_ila_wrapper_U/bd_ila_i/tlp_dma_wr_1/tlp_dma_wr_U/inst/desc_bytes_int_reg[*]/C}] -to [get_pins {app/bd_ila_wrapper_U/bd_ila_i/tlp_dma_wr_1/tlp_dma_wr_U/inst/desc_bytes_int_reg[*]/D}]
set_false_path -from [get_pins {app/bd_ila_wrapper_U/bd_ila_i/tlp_dma_wr_1/tlp_dma_wr_U/inst/desc_bytes_int_reg[*]/C}] -to [get_pins {app/bd_ila_wrapper_U/bd_ila_i/tlp_dma_wr_1/tlp_dma_wr_U/inst/size_int_reg[*]/D}]
set_false_path -from [get_pins {app/bd_ila_wrapper_U/bd_ila_i/tlp_dma_wr_1/tlp_dma_wr_U/inst/tlp_hdr_len_reg[*]/C}] -to [get_pins {app/bd_ila_wrapper_U/bd_ila_i/tlp_dma_wr_1/tlp_dma_wr_U/inst/desc_addr_int_reg[*]/CE}]

# set_false_path -from [get_pins {app/bd_ila_wrapper_U/bd_ila_i/zzlab_env_ctrl_0/inst/int_out_ap_rst_n_reg[*]/C}] -to [get_pins {app/bd_ila_wrapper_U/bd_ila_i/tlp_dma_wr_2/tlp_dma_wr2_U/inst/*/CLR}]
set_false_path -from [get_pins {app/bd_ila_wrapper_U/bd_ila_i/tlp_dma_wr_2/tlp_dma_wr2_U/inst/bytes_int_reg[*]/C}] -to [get_pins {app/bd_ila_wrapper_U/bd_ila_i/tlp_dma_wr_2/tlp_dma_wr2_U/inst/addr_next_int_reg[*]/D}]
set_false_path -from [get_pins {app/bd_ila_wrapper_U/bd_ila_i/tlp_dma_wr_2/tlp_dma_wr2_U/inst/size_int_reg[*]/C}] -to [get_pins {app/bd_ila_wrapper_U/bd_ila_i/tlp_dma_wr_2/tlp_dma_wr2_U/inst/addr_next_int_reg[*]/D}]